#! /usr/bin/env python
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

include_rules

: ErrorList.h |> ^ sed %f -> %o^ sed -n 's/.*ERROR(\([A-Z_0-9]*\).*/#define \1 nsresult::\1/p' < %f > %o |> ErrorListDefines.h | $(MOZ_ROOT)/dist/include/<installed-headers>

include $(MOZ_ROOT)/build/tup/compile.tup
